name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
          arch: 'x64'

      # ----------------- Compilers per OS -----------------

      - name: Install compilers (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran make

      - name: Setup MSYS2 and mingw-w64 toolchain (Windows)
        if: contains(matrix.os, 'windows')
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gcc-fortran

      - name: Install cmake (Windows)
        if: contains(matrix.os, 'windows')
        shell: pwsh
        run: |
          choco install cmake -y

      - name: Install compilers (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          brew install gcc@12
          # Try to make gfortran-12 available as 'gfortran'
          if command -v gfortran-12 >/dev/null 2>&1; then
            sudo ln -s $(which gfortran-12) $(dirname $(which gfortran-12))/gfortran || true
          fi

      - name: Check gfortran (Windows)
        if: contains(matrix.os, 'windows')
        shell: bash
        run: |
          if command -v gfortran >/dev/null 2>&1; then
            gfortran --version
          else
            echo "gfortran not found in MSYS2/mingw PATH; aborting.";
            exit 1;
          fi

      - name: Check gfortran (Unix)
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          if command -v gfortran >/dev/null 2>&1; then
            gfortran --version
          else
            echo "gfortran not found on runner; aborting build.";
            exit 1;
          fi

      # ----------------- Compile sources -----------------

      - name: Compile sources (Windows)
        if: contains(matrix.os, 'windows')
        shell: bash
        run: |
          make -C src -f makefile EXT=.exe

      - name: Compile sources (Linux/macOS)
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          make -C src -f makefile

      # ----------------- Compile shared libraries --------------hh---

      - name: Compile libraries (Windows)
        if: contains(matrix.os, 'windows')
        shell: pwsh
        run: |
          make -C src -f makefile FLINK='-shared' FFLAGS='-fPIC -O3' EXT=.dll

      - name: Compile libraries (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          make -C src -f makefile FLINK='-shared' FFLAGS='-fPIC -O3' EXT=.so

      - name: Compile libraries (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          make -C src -f makefile FLINK='-shared' FFLAGS='-fPIC -O3' EXT=.dylib

      # ----------------- Julia tests -----------------

      - name: Setup julia testing framework
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests (through julia)
        uses: julia-actions/julia-runtest@latest
