function [] = function_to_set_graphics_defaults (print)

if print

    set(groot, ...
        'DefaultAxesFontSize',14, ...
        'DefaultTextFontSize',14, ...
        'DefaultLegendFontSize',13, ...
        'DefaultAxesLabelFontSizeMultiplier',1.1, ...
        'DefaultAxesTitleFontSizeMultiplier',1.1, ...
        'DefaultLineLineWidth',1.5, ...
        'DefaultAxesLineWidth',1, ...
        'DefaultAxesBox','on', ...
        'DefaultAxesTickDir','in')
%        'DefaultFigureColor','w');

    set(groot,'DefaultAxesXMinorTick','on');
    set(groot,'DefaultAxesYMinorTick','on');

else

    set(groot, ...
        'DefaultAxesFontSize',28, ...
        'DefaultTextFontSize',28, ...
        'DefaultLegendFontSize',26, ...
        'DefaultAxesLabelFontSizeMultiplier',1.1, ...
        'DefaultAxesTitleFontSizeMultiplier',1.1, ...
        'DefaultLineLineWidth',3, ...
        'DefaultAxesLineWidth',2, ...
        'DefaultLineMarkerSize',10, ...
        'DefaultAxesTickDir','in', ...
        'DefaultAxesBox','on')
%        'DefaultFigureColor','w');

    set(groot,'DefaultAxesXMinorTick','off');
    set(groot,'DefaultAxesYMinorTick','off');

end

set(groot, ...
    'DefaultLineLineStyle','-', ...
    'DefaultLineMarker','none');

end