
% Given a 2-D tab Perple_X tab file generated by WERAMI in computational mode 2,
% that defines Z(X,Y), extract_o_bat extracts the X-Y coordinates of a user 
% specified contour of Z.

% This script can be used to extract the P-T coordinates of adiabats [S(P,T)] or isochors [V(P,T)
% or rho(P,T)] from a phase diagram section computed as a function of P and
% T. Once the coordinates of the adiabat or iscochor have been extracted
% they can be used as input in WERAMI (mode 4) to extract properties along
% the isochor or adiabat. Alternatively the coordinates can be used as
% input for a 1-dimensional adiabatic or isochoric calculation with VERTEX. 

% JADC June 26, 2011

clear all; clf;

[x,y,a,xname,yname,zname,nvar,mvar,nrow,dnames,titl] = function_to_get_perple_x_file; %open the Perple_X file

function_for_extract_o_bat (x,y,a,xname,yname,zname,nvar,mvar,nrow,dnames,titl);

